# file .travis.yml

language: julia

julia:
  - nightly
  - 1.0

os:
  - linux

notifications:
  email: false

env:
  - PYTHON="python"

addons:
  apt:
    packages:
      - python-numpy
      - python-Cython
      - python-ripser

coveralls: true
