# file .travis.yml

language: julia

julia:
  - nightly
  - 1.0

os: 
  - linux 

before_installation:
  - sudo apt-get install python3 && sudo apt-get install python3-pip && sudo pip3 install Cython && sudo pip3 install ripser
  - julia -e 'ENV["PYTHON"]="python"'

coveralls: true

