# language: julia
#
# os:
#   - linux
# julia:
#   - 1.0
#   - nightly
# matrix:
#   #- PYTHON = python  # python 2.7
#   - PYTHON=python3 # python 3.5
#   #- PYTHON=Conda-python
# matrix:
#   allow_failures:
#     - julia: nightly
# branches:
#   only:
#     - master
# notifications:
#   email: false
#
# after_success:
#   - julia -e 'using Pkg; import ProteinPersistent; cd(joinpath(dirname(pathof(ProteinPersistent)), ".."));Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'

language: julia
os:
    - linux
julia:
    - nightly
    - 1.0
notifications:
    email: false
env:
    - PYTHON=""
    
