# file .travis.yml

language: julia

julia:
  - nightly
  - 1.0

os:
  - linux

notifications:
  email: false

matrix:
  - PYTHON="python"

before_install:
 - (sudo apt-get install python python-pip)
 - (sudo pip install Cython)
 - (sudo pip install ripser)
 - julia -e 'ENV["PYTHON"]="/usr/local/bin/python"; using Pkg; Pkg.add("PyCall"); Pkg.build("PyCall")'

coveralls: true
