# language: julia
#
# os:
#   - linux
# julia:
#   - 1.0
#   - nightly
# matrix:
#   #- PYTHON = python  # python 2.7
#   - PYTHON=python3 # python 3.5
#   #- PYTHON=Conda-python
# matrix:
#   allow_failures:
#     - julia: nightly
# branches:
#   only:
#     - master
# notifications:
#   email: false
#
# after_success:
#   - julia -e 'using Pkg; import ProteinPersistent; cd(joinpath(dirname(pathof(ProteinPersistent)), ".."));Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'

sudo: required
dist: trusty
language: python
os:
    - linux
python:
  - "2.7"

install:
  - which python
  - echo $PYTHON
  - export PATH=$(which python):$PATH
  - export PYTHON=$(which python)
  - export JULIA_LOAD_PATH=$(abspath $(dir $(lastword $(MAKEFILE_LIST))))
  - export PYTHONPATH=$(which python):$PYTHONPATH

  # install cython and ripser python library
  - sudo pip install Cython
  - sudo pip install scikit-tda

  # Installing Julia
  - sudo add-apt-repository -y ppa:staticfloat/juliareleases -y
  - sudo add-apt-repository -y ppa:staticfloat/julia-deps
  - sudo -E apt-get -yq update &>> ~/apt-get-update.log
  - sudo apt-get install libgmp3-dev
  - sudo apt-get install julia
  - julia -e 'versioninfo()'
  - julia -E 'Pkg.update()'
  - julia -e 'Pkg.add("PyCall")'

# command to run tests
script:
  - julia test/runtests.jl


after_success:
  - julia -e 'using Pkg; import ProteinPersistent; cd(joinpath(dirname(pathof(ProteinPersistent)), ".."));Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
