# file .travis.yml

language: julia

julia:
  - nightly
  - 1.0

os:
  - linux

notifications:
  email: false

env:
  - PYTHON=""

before_installation:
  - julia -e 'using Pkg; Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.add("Conda"); using Conda; Conda.update(); Conda.add("Cython"); Conda.add("ripser");'

coveralls: true
